version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      api-network:
        ipv4_address: 10.5.0.3

  spring_app:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      api-network:
        ipv4_address: 10.5.0.2

networks:
  api-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
